### ISSUE TITLE
event-watcher: Parsed contract log

### ISSUE THREAD

**Issue by ackintosh** [cryptoeconomicslab/plasma-rust-framework#115]
## Is your feature request related to a problem? Please describe.

We can use the data but which needs to be parsed. it's hassle to me...

```rust
watcher.subscribe(Box::new(|log| {
    // data: Bytes([............])
    println!("data: {:?}", log.data); 
}
```

## Describe the solution you'd like

I'd like to suggest that passing the parsed contract log (`parsed_params` below) as second argument to the closure. (or make the `log` contains parsed its data.)

```rust
let event = Event {
    name: "Deposit".to_owned(),
    inputs: vec![
        EventParam {
            name: "depositor".to_owned(),
            kind: ParamType::Address,
            indexed: false,
        },
        EventParam {
            name: "amount".to_owned(),
            kind: ParamType::Uint(256),
            indexed: false,
        }
    ],
    anonymous: false,
};

// ...


watcher.subscribe(Box::new(|log, parsed_params| {

    // LogParam { name: "depositor", value: Address(0x627306090abab3a6e1400e9345bc60c78a8bef57) }
    println!("{:?}", parsed_params[0]);

    // LogParam { name: "amount", value: Uint(1) }
    println!("{:?}", parsed_params[1]);
}
```

I'll tackle the issue if it makes sense. :sparkles:

**Comment by tkmct** [comment]
Thank you for the suggestion.
It really makes sense but in current situation, ethabi crate is not yet ready to decode dynamic tuple type which we use in our contracts. We are currently working on it by forking ethabi and make it possible to decode dynamic tuple.
So, please wait for our update.

**Comment by ackintosh** [comment]
Thank you for your quick reply. I'm looking for the update. ✨

**Comment by tkmct** [comment]
@ackintosh 
we've patched ethabi to encode and decode tuple.
If you're still interested in this, we really appreciate it if you give it a shot!

**Comment by ackintosh** [comment]
Yeah! I'll start working on this issue on this weekend. 😉
