### ISSUE TITLE
Research & Writing about OVM

### ISSUE THREAD

**Issue by tkmct** [cryptoeconomicslab/plasma-rust-framework#117]
## Overview
- Post one article about OVM. Something like
- How to Express Plasma using OVM language.
- Discussion about OVM.
- Our stance
- What is Universal client? (future work)

**Comment by tkmct** [comment]
- How to construct more complicated logic using primitive expression.
- The gap we need to fill.

**Comment by syuhei176** [comment]
## Outline of the article

https://scrapbox.io/cryptoeconomicslab/Discussion_Jul_23#5d368a1852252b0000291e06

**Comment by yuriko627** [comment]
this issue was merged into another one here on the publication repo: https://github.com/cryptoeconomicslab/publications/issues/1
