### ISSUE TITLE
Implement Layer2 Data Syncer

### ISSUE THREAD

**Issue by syuhei176** [cryptoeconomicslab/plasma-rust-framework#125]
## Is your feature request related to a problem? Please describe.

child of #119 

Data Syncer is pub-sub like networking + database layer. We can share state_updates not only for Plasma but also for state channel through Data Syncer with other clients.

## Describe the solution you'd like

Implement Data Syncer with Rust. One consideration is it seems hard to implement Data Syncer for multiplatform(especially if we don't use HTTP). If we implement the pub-sub network with a centralized server, it becomes easier to build.

**Comment by syuhei176** [comment]
## Examples

pubs db's general usage for layer 2.

### State channel(polling latest state)

```
loop {
  let latest_state = L2.get('state_channel_id')
}
```

### Plasma

```
loop {
  // get latest transaction and witness
  let latest_tx = L2.db.get('plasma_id/latest_tranaction')
  if(latest_tx) {
    // sync state. ranged is wrapper of db.
    let status_update = L2.rangedb.get('plasma_id/state', latest_tx .start, latest_tx .end)
  }
}
```

**Comment by tkmct** [comment]
I wonder if this is general for OVM or some part is specific for some design.
For example, `L1.db.get` seems to get from CommitmentContract which is plasma specific L1 contract. And L2 call might also become specific for some design.

**Comment by syuhei176** [comment]
> I wonder if this is general for OVM or some part is specific for some design.
> For example, `L1.db.get` seems to get from CommitmentContract which is plasma specific L1 contract. And L2 call might also become specific for some design.

I think this is general. But I misstated. It's `L1.get` but not `L1.db.get`.
We need `L1.get`, `L1.submitTx`, `L1.claimProperty`, `L1. proveUndecidedContradiction` and `L1. removeContradiction` as general methods. I think the client code corresponding commitment contract should be plasma specific but `L1.get` is general.
