### ISSUE TITLE
Design L1 and L2 adaptors

### ISSUE THREAD

**Issue by syuhei176** [cryptoeconomicslab/plasma-rust-framework#126]
## Description

I think we can make a good abstraction for L1 communicator and L2 Data syncer.

## Describe the solution you'd like

example_decider.rs
```rust
// ex Plasma) submit merkle root
L1.submit(property)

// ex) exit or close channel
let propertyWithProof = L2.get(key)
L1.claimProperty(propertyWithProof)

// ex Channel) receiving latest state in state channel
let event = L2.get(key) // polling?
L2.put(key, event.propertyWithProof) // L2.put is publish data to other clients!

// ex Plasma) receiving coin in Plasma
let event = L1.get_new_event("submit")
L2.put(key, event.propertyWithProof) // L2.put is publish data to other clients!
```

**Comment by syuhei176** [comment]
I think it enable more simple architecture.
<img width="523" alt="Screen Shot 2019-07-25 at 15 40 10" src="https://user-images.githubusercontent.com/1094660/61851647-8351b700-aef2-11e9-948b-4aa01bf56ebc.png">

**Comment by tkmct** [comment]
Where do predicate plugins belong to?

**Comment by syuhei176** [comment]
hm, We need PredicatePluginManager(DeciderManager).

**Comment by syuhei176** [comment]
https://github.com/cryptoeconomicslab/research/pull/9
https://github.com/cryptoeconomicslab/research/pull/10
