### ISSUE TITLE
Enable rustdoc

### ISSUE THREAD

**Issue by syuhei176** [cryptoeconomicslab/plasma-rust-framework#13]
- [x] add minimal comment
- [x] research rustdoc for workspace
- [ ] deploy documents on GitHub page.

**Comment by shogochiai** [comment]
https://github.com/steveklabnik/rustdoc

**Comment by shogochiai** [comment]
Confirmed `cargo doc --open --no-deps --document-private-items` generates docs on local.

![Screen Shot 2019-06-04 at 14 13 47](https://user-images.githubusercontent.com/4891004/58852799-e5e8bc80-86d2-11e9-9418-0c9291e2e3d8.png)

**Comment by shogochiai** [comment]
You can see workspace tips as well
![Screen Shot 2019-06-04 at 14 49 52](https://user-images.githubusercontent.com/4891004/58854330-ed5e9480-86d7-11e9-8161-666730668dca.png)
