### ISSUE TITLE
[Discussion] pub-sub datastore?

### ISSUE THREAD

**Issue by tkmct** [cryptoeconomicslab/plasma-rust-framework#131]
Utilize a centralized server at first.

**Comment by syuhei176** [comment]
Also check https://github.com/plasma-group/point-to-point-messaging

**Comment by syuhei176** [comment]
My original idea is from https://github.com/cryptoeconomicslab/plasma-rust-framework/issues/125 and https://github.com/cryptoeconomicslab/plasma-rust-framework/issues/126

> Data Syncer is pub-sub like networking + database layer. We can share state_updates not only for Plasma but also for state channel through Data Syncer with other clients.

> Implement Data Syncer with Rust. One consideration is it seems hard to implement Data Syncer for multiplatform(especially if we don't use HTTP). If we implement the pub-sub network with a centralized server, it becomes easier to build.


```
// ex) exit or close channel
let propertyWithProof = L2.get(key)
L1.claimProperty(propertyWithProof)

// ex Channel) receiving latest state in state channel
let event = L2.get(key) // polling?
L2.put(key, event.propertyWithProof) // L2.put is publish data to other clients!

// ex Plasma) receiving coin in Plasma
let event = L1.get_new_event("submit")
L2.put(key, event.propertyWithProof) // L2.put is publish data to other clients!
```
