### ISSUE TITLE
[L1 Contract Adaptor] Create abstract L1 Contract Adaptor

### ISSUE THREAD

**Issue by tkmct** [cryptoeconomicslab/plasma-rust-framework#134]
Create Abstract L1 Contract adaptor

* submit transaction
* get events
* handle events

**Comment by syuhei176** [comment]
https://github.com/tokio-rs/mio

**Comment by tkmct** [comment]
I'll fix event-watcher first.

**Comment by tkmct** [comment]
@syuhei176 do you have any insights about mio?

**Comment by syuhei176** [comment]
> @syuhei176 do you have any insights about mio?

No I don't have.

**Comment by tkmct** [comment]
@syuhei176 
Do you think it's good to run event-watcher in contract-adaptor?

**Comment by tkmct** [comment]
I think it's better to manage all networking code in one place.
which manage all contract-adaptors and watch events, get L2 state updates, data syncing.

**Comment by syuhei176** [comment]
@tkmct Yeah I think so! Let's talk about minimal requirements.
I believe we need simple "sync methods between L1 data and client storage".
