### ISSUE TITLE
Should change type of `QuantifierResult.results`

### ISSUE THREAD

**Issue by syuhei176** [cryptoeconomicslab/plasma-rust-framework#148]
## Describe the bug

Current QuantifierResult.results's type is `Vec<Bytes>`. ( In typescript implementation, it's `any[]` )
https://github.com/cryptoeconomicslab/plasma-rust-framework/blob/master/ovm/src/types/core.rs#L230

This implementation has a problem. For example, when we wanna put `Property` into result we can't serialize some property such as PropertyFactory.

## Solution

Let's discuss

**Comment by syuhei176** [comment]
One solution is using enum for Quantifier Result.

```
enum VecForQuantifierResult {
  VecInteger(Vec<Integer>),
  VecMessage(Vec<Message>),
  VecProperty(Veg<Proerty>),
}
struct QuantifierResult {
  results: VecForQuantifierResult,
  all_results_quantified: bool,
}
```

**Comment by tkmct** [comment]
In my opinion, quantifiers are just filtering functions for some set of data.
We need to do something like `QuantifierResult.results.map(into_property)` to make quantified results into a set of property.
some logic to reduce property into data and some logic to make data into property is needed?.

**Comment by tkmct** [comment]
```rust
struct QuantifierResult {}

let result = quantifier_result.get_results().map(into_property);

```

**Comment by syuhei176** [comment]
In this example we should serialize second nested `PropertyFactory`.
```
ForAllSuchThat(
  Quantifier(),
  PropertyFactory((property) => {
     return ForAllSuchThat(
      Quantifier(),
      PropertyFactory((someIntData) => {
         return ...
      }
     )
  })
)
```
