### ISSUE TITLE
Design plasma exit claim

### ISSUE THREAD

**Issue by syuhei176** [cryptoeconomicslab/plasma-rust-framework#162]
## Description

Designing plasma exit claim and implementing required deciders.

https://github.com/plasma-group/ovm/blob/master/specs/optimistic-rollup/optimistic-rollup-visual-overview.md#2-plasma

**Comment by syuhei176** [comment]
https://github.com/plasma-group/ovm/blob/master/specs/optimistic-rollup/optimistic-rollup-visual-overview.md#2-plasma

<img width="770" alt="Screen Shot 2019-08-17 at 19 42 28" src="https://user-images.githubusercontent.com/1094660/63210481-dac9f800-c129-11e9-988e-4ffe8f3823d2.png">

The problem is that “claim” has “variable” and how we express “variable” and how smart contract verify “variable”.
b and c are arguments of claim
plasma_exit_claim(b, c) := …

### In client

```
And(
  Not(is_deprecated(b, c)),
  ForAllSuchThat(
    RangeQuantifier(c),
    (coinId) => {
      return ForAllSuchThat(
        LessThanQuantifier(b),
        (blockNumber) => {
          return included_state_update(block_number, coin_id)
        }
      )
    }
  )
)
```

### In smart contract

How do we express and verify?

**Comment by syuhei176** [comment]
# Plasma claims

first draft!

## Plasma checkpoint claim

```
plasma_checkpoint(b, c) :=
ForAllSuchThat(
    LessThanQuantifier(b),
    (blockNumber) => {
        return ForAllSuchThat(
            BlockRangeQuantifier(blockNumber, c),
            (state_update) => {
                return And(
                    included_state_update(block_number, state_update),
                    is_deprecated(block_number, state_update)
                )
            }
        )
    }
)
```

## deprecated claim

Ownership Predicate

```
is_deprecated(b, s) :=
signature_exists(
    construct_transaction(b, s.coin_range),
    state.owner
)
```

## Plasma exit claim

```
plasma_exit(b, s) :=
And(
    Not(is_deprecated(b, s)),
    plasma_checkpoint(b, s.coin_range)
)
```

**Comment by shogochiai** [comment]
# Questions
- Does `b` have the type of `Int`? (i.e. block_number)
- Does `c` have the type of `Checkpoint`?
- Does `s` have the type of `StateUpdate`?
- Does `pre_state` have the type of `StateUpdate`?
- Is the type `StateObject` merged into `StateUpdate`?

**Comment by syuhei176** [comment]
> # Questions
> * Does `b` have the type of `Int`? (i.e. block_number)

yes

> * Does `c` have the type of `Checkpoint`?

c is coinId

> * Does `s` have the type of `StateUpdate`?

s is StateUpdate for plasma

> * Does `pre_state` have the type of `StateUpdate`?

pre_state is StateUpdate

> * Is the type `StateObject` merged into `StateUpdate`?

I didn't define StateObject, but I think it's property.

**Comment by syuhei176** [comment]
## startExit with/without verifyInclusion

```
plasma_exit_with_verify_inclusion(b, s) :=
And(
    included_state_update(b, s),
    Not(is_deprecated(b, s)),
    plasma_checkpoint(b, s.coin_range)
)

plasma_exit_without_verify_inclusion(b, s) :=
And(
    Not(is_deprecated(b, s)),
    plasma_checkpoint(b, s.coin_range)
)

```

**Comment by syuhei176** [comment]
### startExit with/without verifyInclusion

If user call `claimProperty(exitProperty)` and `claimProperty(verifyInclusion)`, and decide inclusion soon.
Anybody can't prove undecidedContradiction with `Not(verifyInclusion)`.

**Comment by syuhei176** [comment]
```
{
    "initial": [BlockNumber, StateUpdate],
    "body": [
        And,
        [
            [Not, [IsDeprecated, [0, 1]]],
            [
                ForAllSuchThat,
                [LessThanQuantifier, 0],
                [
                    ForAllSuchThat,
                    [BlockRangeQuantifier, 1],
                    [And, [IncludedInBlock, [2, 3]], [IsDeprecated, [2, 3]]]
                ]
            ]
        ]
    ]
}
```

**Comment by syuhei176** [comment]
related to https://github.com/plasma-group/ovm/issues/4

**Comment by syuhei176** [comment]
We should update some of plasma properties.

### Checkpoint claim

We should check inclusion and exclusion in `BlockRangeQuantifier` to ensure `state_update` must be within `coin_range`.

```
plasma_checkpoint(block_number, coin_range) :=
ForAllSuchThat(
    LessThanQuantifier(block_number),
    (b) => {
        return ForAllSuchThat(
            BlockRangeQuantifier(b, coin_range),
            (state_update) => {
                return IsDeprecated(state_update)
            }
        )
    }
)
```

### Exit claim

For generalized Plasma, we should check state transition. Important note is `pre_state_data ` is embedded in property as constant value.

```
StateUpdate {
  block_number: 10,
  coin_range: [0, 100],
  deposit_contract: '0x...',
  property: 'claim for deprecated logic',
}

```
state_update.property =
  there exists tx such that IsSameCoinRange(state_update.coin_range)
    VerifyStateTransition(pre_state_data, tx)
```
