### ISSUE TITLE
EvaluatesDecider

### ISSUE THREAD

**Issue by syuhei176** [cryptoeconomicslab/plasma-rust-framework#176]
## Is your feature request related to a problem? Please describe.

How do we decide byte code provided by quantifier?

for example, plasma with predicate.

```
for all stateUpdate included in block:
  And(includedAt(stateUpdate), deprecated(stateUpdate))
```

## Describe the solution you'd like

Use meta decider, "EvaluatesDecider", which evaluate input as decider.

```
for all stateUpdate included in block:
  And(includedAt(stateUpdate), for all property such that property in stateUpdate: EvaluatesDecider(property))
```

**Comment by tkmct** [comment]
In this example, `deprecated(stateUpdate)` has an executable byte code in it?
I'm not sure what kind of `byte code` is executable in this decider.

**Comment by syuhei176** [comment]
`byte code` is data of  merle-leaf and also abi encoded Property.

**Comment by tkmct** [comment]
so the decider needs to decide using merkle-leaf and Property to decide deprecation.

**Comment by syuhei176** [comment]
From decider's point of view, just byte-data is provided and it's Property. So the decider should parse byte-data and decide using its property.

**Comment by syuhei176** [comment]
Already we have https://github.com/cryptoeconomicslab/plasma-rust-framework/blob/master/ovm/src/deciders/is_deprecated_decider.rs.
