### ISSUE TITLE
Tasks until and during ethboston

### ISSUE THREAD

**Issue by syuhei176** [cryptoeconomicslab/plasma-rust-framework#184]
### Until EthBoston

- [ ] Implementing Plasma client
- [ ] Adding endpoints for frontend(It helps us if client don't work on Android)
- [x] Preparing a small server for demo
  - ec2-52-196-101-103.ap-northeast-1.compute.amazonaws.com
- [x] Deposit contract and commitment contract
- [x] Publication
- [x] Update README.md

### During EthBoston

- [ ] Building Frontend!
- [x] Designing claim!
- [x] Building deciders on L2
- [x] Making demo!
- [x] Submit to ethboston.devpost.com
- [ ] Building predicate on smart contract

@yuriko627 @tkmct Please confirm your tasks!

**Comment by tkmct** [comment]
Yes! Let's do!
