### ISSUE TITLE
minimal EventWatcher

### ISSUE THREAD

**Issue by syuhei176** [cryptoeconomicslab/plasma-rust-framework#36]
## Description

The ethereum event watcher is a general watching module. We use this as watching events of deposit contract and commit contract.

## References

See also https://github.com/plasma-group/pigi/tree/01ab31380c8058709574647ee3037d28702e4e18/packages/watch-eth.

https://docs.plasma.group/projects/spec/en/latest/src/04-client-architecture/event-watcher.html

**Comment by tkmct** [comment]
I'll take this if it's okay.

**Comment by syuhei176** [comment]
@tkmct off course OK!

**Comment by syuhei176** [comment]
It may be similar to https://github.com/cryptoeconomicslab/plasma-rust-framework/issues/56.
