### ISSUE TITLE
Creating Experimental Client for Android app

### ISSUE THREAD

**Issue by omuomugin** [cryptoeconomicslab/plasma-rust-framework#47]
## WHAT
- Create Android Client which can communicate with https://github.com/cryptoeconomicslab/plasma-rust-framework through NDK
- Researching how evm verifier can run on Android app (#35 )

**Comment by syuhei176** [comment]
Created repository for this issue.
https://github.com/cryptoeconomicslab/plasma-android-sdk/issues
