### ISSUE TITLE
add db adaptor for child chain

### ISSUE THREAD

**Issue by syuhei176** [cryptoeconomicslab/plasma-rust-framework#5]
### References

please follow https://github.com/plasma-group/pigi/tree/01ab31380c8058709574647ee3037d28702e4e18/packages/core/src/app/common/db
 for child chain db adaptor.

**Comment by shogochiai** [comment]
I'm gonna take this if @syuhei176 don't feel blocked

**Comment by syuhei176** [comment]
- [ ] core db adaptor 
- [ ] mem db impl
- [ ] leveled impl
- [ ] postgres impl

**Comment by syuhei176** [comment]
range db will be added in pigi. This db is abstraction for range(to store current state and exitableRange)
https://github.com/plasma-group/pigi/pull/193/files#diff-d380414d866abe2ed2effb675d5df440

**Comment by shogochiai** [comment]
Noice catch! Will see that!

**Comment by shogochiai** [comment]
Pigi db abstractions are directly consuming leveldb though, I'm gonna insert one more layer to enable switching leveldb/postgressdb

**Comment by shogochiai** [comment]
Parity is [using](https://github.com/paritytech/parity-ethereum/search?q=KeyValueDB&unscoped_q=KeyValueDB) `KeyValueDB` struct which is very standard in Rust.

This would be a good "CommonDB" interface of our usecase.

**Comment by shogochiai** [comment]
KeyValueDB was a dedicated interface for RocksDB

**Comment by syuhei176** [comment]
move to https://github.com/cryptoeconomicslab/plasma-rust-framework/issues/34
