### ISSUE TITLE
Deployment to ghpage is failing

### ISSUE THREAD

**Issue by syuhei176** [cryptoeconomicslab/plasma-rust-framework#67]
Please check 2 things

* deployment is failing
* please consider secure encryption. https://docs.travis-ci.com/user/environment-variables#defining-encrypted-variables-in-travisyml

**Comment by shogochiai** [comment]
I'm dealing with that

**Comment by shogochiai** [comment]
Symptom
https://github.com/cryptoeconomicslab/plasma-rust-framework/pull/52#issuecomment-499547830

Similar bug
https://github.com/travis-ci/travis-ci/issues/8548#issuecomment-335012015

Struggling on it.

**Comment by shogochiai** [comment]
I feel push protection doing something wrong

**Comment by shogochiai** [comment]
personal access token requires SSO of organization via personal setting page
https://help.github.com/en/articles/authorizing-a-personal-access-token-for-use-with-a-saml-single-sign-on-organization

**Comment by shogochiai** [comment]
SAML SSO is only for the within enterprise cloud, maybe?

**Comment by shogochiai** [comment]
![sso-whitelist-button](https://user-images.githubusercontent.com/4891004/59546888-32a08300-8f70-11e9-8a7f-cf60b7106030.png)

I can't see this SSO button for now

**Comment by syuhei176** [comment]
@shogochiai Are there any update?

**Comment by syuhei176** [comment]
Switch back to Trusty or wait the fixed PR below.
https://github.com/travis-ci/dpl/pull/1005
https://travis-ci.community/t/failed-to-deploy-because-of-ruby-error/1143/7
