### ISSUE TITLE
[CLIENT] Plasma Aggregator

### ISSUE THREAD

**Issue by tkmct** [cryptoeconomicslab/plasma-rust-framework#90]
# Description 
## Client
- [x] handle_tx
  - listen to other clients
  - validate tx
- [x] submit_block
  - query tx from db
  - block generation
  - block submission
  - broadcasting
- [x] tx_db (queue)
  - store tx sent by other clients
- [x] state_db
  - store current state to validate tx

## Contract
- [x] Commitment Contract

**Comment by syuhei176** [comment]
Done by these PRs
https://github.com/cryptoeconomicslab/plasma-rust-framework/pull/187
https://github.com/cryptoeconomicslab/plasma-rust-framework/pull/217
