### ISSUE TITLE
Wallet DB and Wallet Manager

### ISSUE THREAD

**Issue by syuhei176** [cryptoeconomicslab/plasma-rust-framework#93]
## Is your feature request related to a problem? Please describe.

Store private key securely.

## Describe the solution you'd like

Use [Key store](https://theethereum.wiki/w/index.php/Accounts,_Addresses,_Public_And_Private_Keys,_And_Tokens).

## Describe alternatives you've considered

the raw private key?

## Additional context

http://spec.plasma.group/en/latest/src/05-client-architecture/wallet.html

**Comment by tkmct** [comment]
wallet db to manage sessionKey to privateKey.

**Comment by tkmct** [comment]
#215
