### ISSUE TITLE
Update SyncManager for first deposit and transfer

### ISSUE THREAD

**Issue by syuhei176** [cryptoeconomicslab/plasma-rust-framework#97]
## Description

Update SyncManager to complete deposit flow. SyncManager knows all commit contract and deposit contract addresses. So, SyncManager can initialize EventWatcher and subscribe to each contract.

1. Subscribe [checkpoint event](https://github.com/plasma-group/pigi/blob/master/packages/contracts/contracts/Deposit.sol#L107) from deposit contract and change the state of state manager. (deposit transaction emit `checkpoint` event)
2. Subscribe block submitted event from commitment contract, and get proof from the aggregator and change the state of state manager.

**Comment by tkmct** [comment]
I'm taking this!
