### ISSUE TITLE
Replace the db of event-watcher to core db crate

### ISSUE THREAD

**Issue by syuhei176** [cryptoeconomicslab/plasma-rust-framework#99]
See https://github.com/cryptoeconomicslab/plasma-rust-framework/pull/86#discussion_r297739242.

**Comment by tkmct** [comment]
@syuhei176 I created PR, is this what you meant?
#101

**Comment by syuhei176** [comment]
@tkmct yeah, but I think EventDb can be implemented by [KVS](https://github.com/cryptoeconomicslab/plasma-rust-framework/blob/master/db/src/traits/kvs.rs#L94).
like [rangeDb](https://github.com/cryptoeconomicslab/plasma-rust-framework/blob/master/db/src/impls/rangedb.rs#L16).
There are already memory and leveled impls for KVS. So, if you implement EventDb by KVS, you can use both implementations.

**Comment by tkmct** [comment]
Ah, I got it.
So, all I have to do is to create EventDbImpl using KVS and put it along with rangedb. is that correct?

**Comment by tkmct** [comment]
I'll change it quick!!

**Comment by tkmct** [comment]
@syuhei176 oh and another thing is do you prefer eventdb or event_db?

**Comment by syuhei176** [comment]
> Ah, I got it.
> So, all I have to do is to create EventDbImpl using KVS and put it along with rangedb. is that correct?

`EventDb` should be in `event-watcher, like [`state_db`(https://github.com/cryptoeconomicslab/plasma-rust-framework/tree/master/client/src/state)

> @syuhei176 oh and another thing is do you prefer eventdb or event_db?

for filename? event_db is good.

**Comment by tkmct** [comment]
okay, I think I understood perfectly

**Comment by tkmct** [comment]
#102
